### ISSUE TITLE
Is this useable?

### ISSUE THREAD

**Issue by petersmithca** [humhub/humhub-modules-cfiles#1]
Just wondering on the state of this module

**Comment by MalteHorstmann** [comment]
We tried it on our intern HumHub installation, works partial. You can already upload Files and download them again. Folder creation diddn't worked and other details are missing. Upload status feedback to mention one.

Probably someone from HumHub could tell the community if help is wished-for?

**Comment by petersmithca** [comment]
Thank you, I didn't know about the community till after I posted this.  The developers assure me it is still going to happen, just so many things to do.  I appreciate your comment and experience!

**Comment by rohanpoddar** [comment]
DO we have a timeline when this will be finished ? Can we use this in production right now ?

**Comment by buddha87** [comment]
A new version was released few weeks ago, should be stable now beside minor bugs.
