### ISSUE TITLE
Datenbank nicht angelegt

### ISSUE THREAD

**Issue by Havok75** [humhub/humhub-modules-cfiles#10]
bei mir hats die Datenbanken dazu nicht angelegt. kann mir jemand den Befehl dazu geben, das ich die manuell anlegen kann?. sorry bin in sachen mysql ein Noob

**Comment by buddha87** [comment]
Versuchs mal mit folgendem Befehl im protected Ordner:

`php yii migrate/up --includeModuleMigrations=1`

Und wenn möglich, das nächste mal eher auf englisch schreiben, falls irgendjemand ein ähnliches problem hat. Es gibt übringens in der community https://community.humhub.com/ auch einen "German Space" falls es dir auf Deutsch lieber ist. ;)

**Comment by Havok75** [comment]
ok habs probiert, es kam diese Meldung: No new migration found. Your system is up-to-date.
das nächstemal schreib ich per Google Übersetzer :-)
