### ISSUE TITLE
Auto focus create folder input

### ISSUE THREAD

**Issue by buddh4** [humhub/humhub-modules-cfiles#17]
Auto focus create folder input within the modal

**Comment by StellarisAgency** [comment]
I don't know why this branch is only 0.9.5.2... But for the version 0.9.6 from the market,
you can go in _".../views/edit/modal_edit.php"_ and change the line 20**:**
`<?php echo $form->field($folder, 'title'); ?>`
**Into that:**
`<?php echo $form->field($folder, 'title', ['inputOptions' => ['autofocus' => 'autofocus', 'class' => 'form-control', 'tabindex' => '1']]); ?>`
