### ISSUE TITLE
file permission management?

### ISSUE THREAD

**Issue by ideadel** [humhub/humhub-modules-cfiles#19]
Hi, i think could be a good idea to have specific permission in spaces for file manager module. 
i don't know if i could do at the moment but it will be very useful to manage permission for files also for guests.
I need to enable for guests users to see file module and download files.

**Comment by sparkyman215** [comment]
This would be fantastic, is there a workaround so certain people can only see certain folders?

**Comment by DesertRockxxx** [comment]
is there any changes made?
