### ISSUE TITLE
cfile is not working

### ISSUE THREAD

**Issue by saikishorekate** [humhub/humhub-modules-cfiles#21]
PHP Warning – yii\base\ErrorException

Declaration of humhub\modules\cfiles\Module::enableContentContainer($container) should be compatible with humhub\modules\content\components\ContentContainerModule::enableContentContainer(humhub\modules\content\components\ContentContainerActiveRecord $container)

its the problem when uploaded

**Comment by afg4x4** [comment]
Same problem, same error. I use the latest version of humhub. And when I put cfiles module in modules/cfiles and reload module page in humhub I got the same error.

**Comment by afg4x4** [comment]
To solve the problem you need add in Module.php

**Comment by saikishorekate** [comment]
Yes! working nice....
