### ISSUE TITLE
issue of the root & database error

### ISSUE THREAD

**Issue by saikishorekate** [humhub/humhub-modules-cfiles#23]
Oooops... It looks like you may have taken the wrong turn.
An internal error occurred. Could not load root folder, database not properly initialized.

**Comment by BastusIII** [comment]
Hi, sry for the late reply.

- Did you update the cFiles Version and not execute Module Migrations? -> execute "yii migrate/up --includeModuleMigrations=1"

- Did you manually delete entries in the cfiles_folder table in the database? -> Try disabling the in the space module and reenabling it again, if possible. (You will loose files uploaded via cFiles Module in that space)

- Anything else? Try disabling the module in the space and reenabling it again, if possible. Try to completely disable the module and enable it again. (You will loose all data uploaded via cFiles Module unfortunately)
