### ISSUE TITLE
can't change the size of max upload

### ISSUE THREAD

**Issue by clairedc** [humhub/humhub-modules-cfiles#24]
When I try to change the size of max upload for files in the admin, it doesn't work. Changes are not saved.
Thanks for your help.

**Comment by buddha87** [comment]
Which HumHub version are you using and are there any errors in the logs?

**Comment by clairedc** [comment]
I use the latest version of Humhub 1.1.1 and there is no error in logs.
Tanks for your help !

**Comment by buddha87** [comment]
So if you go to "Admin -> Settings -> Advanced -> Files" and change the Max upload file size press Save and reload the the page the settings are not adopted? I could not recreate the issue.

**Comment by clairedc** [comment]
Yes, exactly. Is it a way to change this size directly in a config file ?

**Comment by buddha87** [comment]
This is set in the database table 'settings' with name 'maxFileSize' not the value is stored in bytes.

**Comment by clairedc** [comment]
Actually, it works with "2" (Mo) but not with "1,7" or "1.7" ! Is it normal ?

**Comment by buddha87** [comment]
Yes, there should also be a error message above the form but as I tested it the error was not very obvious ;)

**Comment by clairedc** [comment]
Ok, thanks for your support ! Humhub ist echt toll !

**Comment by BastusIII** [comment]
Seems to be solved.
