### ISSUE TITLE
Last update: yii\base\ErrorException !

### ISSUE THREAD

**Issue by StellarisAgency** [humhub/humhub-modules-cfiles#25]
yii\base\ErrorException
Declaration of humhub\modules\cfiles\Module::enableContentContainer($container) should be compatible with humhub\modules\content\components\ContentContainerModule::enableContentContainer(humhub\modules\content\components\ContentContainerActiveRecord $container)

Error 1 in Module.php line 15.
class Module extends ContentContainerModule

**Comment by buddha87** [comment]
Duplicate of https://github.com/humhub/humhub-modules-cfiles/issues/21
