### ISSUE TITLE
Folder: $autoAddToWall = false; without any effect

### ISSUE THREAD

**Issue by groetzinger** [humhub/humhub-modules-cfiles#26]
I would like to disable the output on the wall, when I upload a file or create a folder.
I found in models/File.php and models/Folder.php the entry $autoAddToWall.

When I switch off it in File.php (to false) the wall don't display automatical new files. 
But the entry in Folder.php takes no effect (when I create a new folder, there is an message on the wall).

Thanks for your help!

**Comment by buddh4** [comment]
Just for your info. The latest cfiles version for the upcoming HumHub 1.2 does not create wall entries for folders only for files. Also there will only be 3 file entries visible in a row with a "show more" button if there are more file entries available. The same goes for tasks etc.
