### ISSUE TITLE
BUG: Show raw content of file insted open news about file

### ISSUE THREAD

**Issue by githubjeka** [humhub/humhub-modules-cfiles#29]
When file uploaded by user I can see in notify it

![image](https://cloud.githubusercontent.com/assets/874234/23994527/58664bac-0a56-11e7-96ca-d13df69a2d4c.png)

But when I clicked by it then getted raw content.

![image](https://cloud.githubusercontent.com/assets/874234/23994492/31481d48-0a56-11e7-9be0-456346a636a4.png)

**Comment by luke-** [comment]
Which HumHub version are you using?

**Comment by githubjeka** [comment]
Thanks, Fixed in 1.2.0-beta.3 (master now)
