### ISSUE TITLE
file folder appears on stream which has no cfiles activated

### ISSUE THREAD

**Issue by 001101** [humhub/humhub-modules-cfiles#32]
hello,

have noticed a issue when i am on a space, where no cfiles is enabled, but there are files in the stream. the button 'open file folder' appears next to the image.

when clicking it there comes a ugly error 'this module is not activated in the content cointainer' 
(Dieses Modul ist in diesem Content Container nicht aktiviert!)

greets

**Comment by buddh4** [comment]
Can you somehow reproduce this? 
Does this only happen on a specific space and was the cfile module installed on this space and removed before?
Or do you think those files are from another space?

**Comment by 001101** [comment]
Sorry, forgot the issue and did not try to reproduce it.
But my site has big issues on activating and deactivating modules on spaces, I can't activate the new gallery module and got javascript errors, so something got hurt on updates.

**Comment by buddh4** [comment]
hmm any specific errors?

**Comment by 001101** [comment]
My mistake, activating is working, but only on manual seperate spaces way, but not over admin interface and setting as default, then I just got a loop.

**chrome error log:**
``
VM380:formatted:38 POST https://band9.net/admin/module/set-as-default?moduleId=gallery 500 ()

line 38:    t.apply(u, arguments)
``

``
POST
$('#h246290w1').click(function() {
                $.ajax({"type":"POST","beforeSend":function(){ setModalLoader(); },"success":function(html){ $("#globalModal").html(html); },"url":"/admin/module/set-as-default?moduleId=gallery","data":$('#h246290w1').closest('form').serialize()});
                    return false;
            });
jQuery('#h246290w0').yiiActiveForm([], []);
``

**Comment by buddh4** [comment]
Can you check the Logs for the actual 500 error?
