### ISSUE TITLE
Edit folder does nothing

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub-modules-cfiles#35]
Right-click on a previously created folder, **EDIT**, a modal opens but it does nothing:

![image](https://cloud.githubusercontent.com/assets/12234510/24815148/860cd47e-1bd4-11e7-8cb5-37fd3d7db2e6.png)

**Comment by henridemooij** [comment]
I have the same issue and (as a paying customer) I'd like to see it fixed.
 
The behaviour can even be reproduced on the HumHub demo on Softaculous: https://www.softaculous.com/demos/HumHub

When clicking the edit button, the debug console shows an 'unhandled rejection' error:
_Unhandled rejection (<{"url":"/s/foldername/cfiles/edit/fold...>, no stack trace)_


From the Network console I can see the /s/foldername/cfiles/edit/folder?id=folder_9 come up, that returns a 200 response. 

Opening that url in a new tab, actually shows the edit form. 
I suspect this might be an issue with running HumHub over https.

Other than that, the only thing I can add is that we're running it behind an Nginx proxy.
