### ISSUE TITLE
Some strings are not translateable

### ISSUE THREAD

**Issue by rcheetah** [humhub/humhub-modules-cfiles#45]
Some strings like „Files from the stream“ are not translatable, as they are hardcoded as constants.

**Comment by buddh4** [comment]
Fixed by https://github.com/humhub/humhub-modules-cfiles/commit/6264ecd3fdc11c6e4376efe4a1c7c2b37f4bac56

**Comment by acs-ferreira** [comment]
@buddh4 no version raise?
https://github.com/humhub/humhub-modules-cfiles/blob/master/module.json#L8

**Comment by buddh4** [comment]
normally I do this before the release.
