### ISSUE TITLE
Enh: Index file names

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub-modules-cfiles#47]
Uploaded files (_names_, like `My_Attached_File.zip`)should be indexed and searchable.
So if i search "attached", that file should be highlighted.

**Comment by buddh4** [comment]
Should already be the case: https://github.com/humhub/humhub-modules-cfiles/blob/master/models/File.php#L64

**Comment by acs-ferreira** [comment]
Ok so i have this topic with attached file:
![image](https://user-images.githubusercontent.com/12234510/29448176-a4bc0190-83f5-11e7-8be1-a74065efaadc.png)

Searching it:
![image](https://user-images.githubusercontent.com/12234510/29448194-b3de20ea-83f5-11e7-9bca-7a2dfd4c9be2.png)

**Comment by buddh4** [comment]
k, this would rather be an core issue, please open a new issue in the humhub core repo.
