### ISSUE TITLE
Can't make folder public

### ISSUE THREAD

**Issue by acs-ferreira** [humhub/humhub-modules-cfiles#49]
1 - Can't make folder public (can't check the checkbox), on creation or modification.

![image](https://user-images.githubusercontent.com/12234510/29994627-6cda2b18-8fd4-11e7-9df3-68380596175c.png)

**Comment by buddh4** [comment]
Did you clear your assets before testing those changes?

**Comment by buddh4** [comment]
Furthermore you can't change the file visibility within a private folder. This is discussable, but it's the current logic. (Perhaps this was the issue in your case)

**Comment by acs-ferreira** [comment]
Heuu...i don't understand whats happened, i always do the same way:

```
rm -Rf cfiles
git clone https://github.com/humhub/humhub-modules-cfiles.git cfiles
cd && grunt build-assets
```

And this time **everything goes fine**, only the first point is wrong IMO. When you create a new folder at the `root`, why it can't be public?

**Comment by buddh4** [comment]
Should be resolved now, this probably occured for already created root folders.

**Comment by acs-ferreira** [comment]
It seems OK now, thanks!
