### ISSUE TITLE
Make it Searchable  ?

### ISSUE THREAD

**Issue by CCRS-WEB** [humhub/humhub-modules-cfiles#5]
Hi,

It would nice if searchable in global search engine.

Regards,

**Comment by NiklasA** [comment]
Hi,

i think CCRS-WEB is right. If you create some spaces with a lot of files, a global search engine is necessary. Are there any plans regarding this feature?

Thank you in advance.

Sincerely,
Niklas

**Comment by EtienneDemers** [comment]
[this](https://github.com/humhub/humhub-modules-cfiles/commit/217a390da686023a4cb715b2c491b38d704755c6) commit solves this issue i think...?
