### ISSUE TITLE
Search error

### ISSUE THREAD

**Issue by staxDB** [humhub/humhub-modules-cfiles#56]
If you create a folder with any name and then search for it, the following error message appears:

1. Create a Folder (private or public)
![image](https://user-images.githubusercontent.com/8705799/30683878-5c287560-9eaf-11e7-8c87-587310fcf63e.png)

2. Search for the folder
![image](https://user-images.githubusercontent.com/8705799/30683914-7b0e30fa-9eaf-11e7-9b37-08a39fba286f.png)

**Comment by buddh4** [comment]
Please post the full stack trace under "Administration -> Information -> Logging"

**Comment by boppy** [comment]
To clarify the problem:

It does come up ONLY if Humhub tries to display a result of type FOLDER. Files can be displayed without any problem (at least over here).

My (minimized) stacktrace is
```
yii\base\ErrorException: Trying to get property of non-object in /var/www/PATH_TO_HUMHUB/protected/humhub/modules/stream/actions/Stream.php:308
Stack trace:
#0 /var/www/PATH_TO_HUMHUB/protected/humhub/modules/stream/actions/Stream.php(308): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/PATH_T...', 308, Array)
#1 /var/www/PATH_TO_HUMHUB/protected/humhub/modules/search/views/search/index.php(111): humhub\modules\stream\actions\Stream::renderEntry(Object(humhub\modules\cfiles\models\Folder))
#2 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/base/View.php(330): require('/var/www/PATH_T...')
#3 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/base/View.php(250): yii\base\View->renderPhpFile('/var/www/PATH_T...', Array)
#4 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/base/View.php(152): yii\base\View->renderFile('/var/www/PATH_T...', Array, Object(humhub\modules\search\controllers\SearchController))
#5 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/base/Controller.php(381): yii\base\View->render('index', Array, Object(humhub\modules\search\controllers\SearchController))
#6 /var/www/PATH_TO_HUMHUB/protected/humhub/modules/search/controllers/SearchController.php(89): yii\base\Controller->render('index', Array)
#7 [internal function]: humhub\modules\search\controllers\SearchController->actionIndex()
#8 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/base/Controller.php(156): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/base/Module.php(523): yii\base\Controller->runAction('index', Array)
#11 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/web/Application.php(102): yii\base\Module->runAction('search/search/i...', Array)
#12 /var/www/PATH_TO_HUMHUB/protected/vendor/yiisoft/yii2/base/Application.php(380): yii\web\Application->handleRequest(Object(humhub\components\Request))
#13 /var/www/PATH_TO_HUMHUB/index.php(25): yii\base\Application->run()
#14 {main}                
```

Full HTML Stacktrace at https://gist.github.com/boppy/d2fc57a8d8de4fdffa91b8b3d087c36c

**Comment by buddh4** [comment]
Probably fixed by https://github.com/humhub/humhub/commit/167692a7125278bae4815d4c8981e6878de61074#diff-b171a978d368c757862c46d8bed8a2db

**Comment by boppy** [comment]
Not eventually.

The error message is not displayed any longer, but "the result" is not listed (the only result should be a folder with a matching comment):

![image](https://user-images.githubusercontent.com/749141/31318732-fd4c85ee-ac56-11e7-9865-d1967e0cd7f6.png)

**Comment by buddh4** [comment]
This should be fixed by: https://github.com/humhub/humhub-modules-cfiles/commit/9c9104786b10406894bbd01e2b47ca5398e01c53 which adds a wallentry view for folders.
