### ISSUE TITLE
Can't use cFile on user profile

### ISSUE THREAD

**Issue by groetzinger** [humhub/humhub-modules-cfiles#58]
I can use cFile on **spaces** without any problem. It works fine. But when I want to use the module on a **user profile**, I can activate it, but then I get the message "I have no premissions to upload or edit files...". 

It's possible to create an folder, but I can't delete it. There is no difference, if I'm "normal" user or an administrator.
I can't find any user rights, which I can change for it. Where is the problem of this?

**Comment by buddh4** [comment]
I'll have a look.

**Comment by buddh4** [comment]
Can't reproduce this, which humhub and cfiles version are you usign?

**Comment by groetzinger** [comment]
Humhub 1.2.2 and cFile 0.11.4

I don't know why, but with "my admin user" (the first user I created, but the same group) I can upload files on my user profile. But when I use an other user (with the same user-rights), I get the error message.

**Comment by spoorun** [comment]
Close this; as timed out? @buddh4
