### ISSUE TITLE
404 File not found

### ISSUE THREAD

**Issue by defiantnight** [humhub/humhub-modules-cfiles#59]
I have a slight issue with my system, i have the files plugin active but it shows a 404 when ever the link is clicked so i can not upload/edit files.

Any help would be brill

Thanks

**Comment by buddh4** [comment]
Please be more specific, which link do you mean?

**Comment by jackloh84** [comment]
Hope can help you here http://docs.humhub.org/admin-installation-configuration.html#url-rewriting-optional
