### ISSUE TITLE
Delete a folder?

### ISSUE THREAD

**Issue by Husky110** [humhub/humhub-modules-cfiles#60]
Heyho,

We're evaluating Humhub right now and test out it's features.
Problem is, that we found the files modules and created some testfolders, but were unable to delete them within the interface.
Didn't we just find is or is this still to be released?

**Comment by buddh4** [comment]
You can either delete the folder by using the context menu (right click) or by using the selection menu (checkboxes).

**Comment by Husky110** [comment]
There I could only find the option to compress a folder...

**Comment by buddh4** [comment]
This user seems not to have the permission delete entries.

**Comment by Husky110** [comment]
The admin-user which installed the whole page doesn't have full permissions on default!?
What!?

**Comment by buddh4** [comment]
There are two permissions which can be assigned to the space user groups. 

- Add files
- Manage files
