### ISSUE TITLE
permissions in the profile

### ISSUE THREAD

**Issue by funkycram** [humhub/humhub-modules-cfiles#69]
When a user upload a files in his profile (not in a space), he hasn't have the permission to remove it. But if he goes in his profile stream he can remove this file.

The problem is in `permissions/ManageFiles.php`, $defaultAllowedGroups needs `User::USERGROUP_SELF`. 

See https://github.com/humhub/humhub-modules-cfiles/compare/master...funkycram:patch-1

**Comment by buddh4** [comment]
Should be fixed in the current version.
