### ISSUE TITLE
Zipping files does not work.

### ISSUE THREAD

**Issue by Penguinexpert1** [humhub/humhub-modules-cfiles#8]
Selecting all files then clicking "ZIP Selected files" results in an Error 500 Internal Server Error. This is on both spaces and users. There is no error shown by Developer Console

**Comment by buddha87** [comment]
Do you mean the 'Archive' functionality to download the selected files as zip ?

This is not working for me either if I try to archive files only I get the following error:

```
ZipArchive::close(): Can't remove file: No such file or directory
 in /codebase/humhub/modules/humhub-modules-cfiles/controllers/ZipController.php at line 423 
```

I only can zip and download folders without errors, but they don't contain any files.

**Comment by buddha87** [comment]
Tested on latest master, now I get a userfriendly error but the same bahaviour, Think this is already in progress.

**Comment by Penguinexpert1** [comment]
@buddha87 Any progress on this? Just upgraded cfiles version and the Error 500 still happens whenever I try to ZIP two files together.

**Comment by buddha87** [comment]
Hi, there is a new update available which should fix this issue. (Not tested it myself though)
