### ISSUE TITLE
File description not searchable

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-cfiles#88]
Add description to search attributes

**Comment by MasterMindNET** [comment]
Does it still need to be fixed?

It looks like this (on the latest master branch):
![image](https://user-images.githubusercontent.com/22347676/90309690-4e484600-def3-11ea-81cd-d78cb64337cb.png)

Let us know if there is something to fix here.

**Comment by luke-** [comment]
@MasterMindNET So the text entered under Description is indexed? So you can search for the term "must" in your example?

**Comment by luke-** [comment]
@MasterMindNET Thanks for testing, then we can close this issue.

The build-search should be triggered by the queue/run.
