### ISSUE TITLE
replace ImageConverter library with Imagine

### ISSUE THREAD

**Issue by fae7em** [humhub/humhub-modules-cfiles#90]
## System

Files 0.11.19
HumHub 1.6.3
PHP 7.3.17

## Problem description

When images are uploaded as .zip files, Internal Server Error occurred, Because there are some files in cfile module which use the Humhub ImageConverter library that is replaced to the Imagine library.

## Possible solution

Replace and implement the Imagine library.

**Comment by luke-** [comment]
Did i missed something?

https://github.com/humhub/humhub-modules-cfiles/commit/9bf7eaea1a801eebabc6088a89d4e39c391f5132

**Comment by fae7em** [comment]
Ahhh, No actually I installed cfile through humhub admin panel, and it has problem. I just see your commit now in the unreleased version. Thanks.
