### ISSUE TITLE
Implement Download Counter

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-cfiles#94]

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub-modules-cfiles/pull/95

Please note sometimes browser gets file from cache without access to server, so counter is not increased in such cases, try to open a link in new tab or by right mouse click with menu option "Download".

<img width="961" alt="download_counter" src="https://user-images.githubusercontent.com/6995524/97704817-21eca080-1ac4-11eb-823d-0296aba154f7.png">

**Comment by luke-** [comment]
Very good solution!

Since this is a very specific feature, I would suggest that we make the "Downloads" column in the overview optional. Configurable as checkbox in the Settings module (/cfiles/config). Maybe disabled by default. No matter if this option  is activated or not, we can display the number of downloads in the "Edit dialog".
![image](https://user-images.githubusercontent.com/4736168/97708984-e8169c80-1ab9-11eb-9565-cf4f6da04a8b.png)

What do you think?

**Comment by buddh4** [comment]
Also test the new column on mobile view. On mobile we should only show important columns.

**Comment by yurabakhtin** [comment]
@luke- @buddh4 ok, I implemented new features in commit https://github.com/humhub/humhub-modules-cfiles/pull/95/commits/f813ba5fdb5801d7f47d714ab641919ec150618a
<img width="1149" alt="download_count_settings" src="https://user-images.githubusercontent.com/6995524/97862652-c403c700-1d16-11eb-8f0d-f9b299125c73.png">
