### ISSUE TITLE
File download affects updated_by 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-cfiles#97]
https://github.com/humhub/humhub-modules-cfiles/blob/master/Events.php#L92
Use "update_attributes" here to bypass "updated_by" handling.

**Comment by luke-** [comment]
Can you please take quick look here.

**Comment by luke-** [comment]
Make also sure that the "Creator" Column is using the "Created_by" Attribute

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/humhub-modules-cfiles/pull/98, I apply the `updateAttributes()` so now `updated_at` and `updated_by` are not affected on download counter action.

> Make also sure that the "Creator" Column is using the "Created_by" Attribute

Yes, the `created_by` attribute is used there for first avatar, but if `updated_by` is different then it will be used for second avatar, the code is https://github.com/humhub/humhub-modules-cfiles/blob/master/widgets/views/fileSystemItem.php#L91-L96.
